src/api/urls.py
from rest_framework import routers
from django.urls import include, path

from .views import (
    BillCreateAPIView,
    BillDeleteAPIView,
    BillDetailAPIView,
    BillListAPIView,
    ContactListAPIView,
    BillUpdateAPIView,
)

router = routers.DefaultRouter()

# Default routes
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

# Personal routes
urlpatterns += [
    path('bills/', BillListAPIView.as_view(), name='bill_list'),
    path('bills/create/', BillCreateAPIView.as_view(), name='bill_create'),
    path('bills/<int:id>/delete/', BillDeleteAPIView.as_view(), name='bill_delete'),
    path('bills/<int:id>/details/', BillDetailAPIView.as_view(), name='bill_list'),
    path('bills/<int:id>/edit/', BillUpdateAPIView.as_view(), name='bill_update'),
    path('contacts/', ContactListAPIView.as_view(), name='contact_list'),
]

src/managebill/urls.py
from django.urls import include, path

from .views import (
    #Bill
    BillAddProductView,
    BillCreateView,
    BillDetailsView,
    BillListView,
    #Contact
    ContactCreateView,
    ContactDeleteView,
    ContactDetailsView,
    ContactUpdateView,
    ContactListView,
    #Product
    ProductCreateView,
    ProductDeleteView,
    ProductListView,
    ProductUpdateView,
    #Shop
    ShopCreateView,
    ShopDeleteView,
    ShopListView,
    ShopUpdateView,
)

app_name = 'managebill'

urlpatterns = [
    #Add product to a bill
    path('bill/add/product/<int:id>', BillAddProductView.as_view(), name='bill_add_product'),
    #Bill's create url
    path('bill/create/', BillCreateView.as_view(), name='bill_create'),
    #Bill details url
    path('bill/details/<int:id>', BillDetailsView.as_view(), name='bill_details'),
    #Bill list url
    path('bill/', BillListView.as_view(), name='bills_list'),
    #Contact's urls
    path('contact/', ContactListView.as_view(), name='contacts'),
    # Create a contact
    path('contact/create/', ContactCreateView.as_view(), name='contact_create'),
    #Contact's delete url
    path('contact/delete/<int:id>', ContactDeleteView.as_view(), name='contact_delete'),
    #Contact's details url
    path('contact/details/<int:id>', ContactDetailsView.as_view(), name='contact_details'),
    #Contact's update url
    path('contact/update/<int:id>', ContactUpdateView.as_view(), name='contact_update'),
    #Product's create url
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    #Product's delete url
    path('product/delete/<int:id>', ProductDeleteView.as_view(), name='product_delete'),
    #Product's update url
    path('product/update/<int:id>', ProductUpdateView.as_view(), name='product_update'),
    #Products url
    path('product/', ProductListView.as_view(), name='products'),
    #Shop's create url
    path('shop/create/', ShopCreateView.as_view(), name='shop_create'),
    #Shop's delete url
    path('shop/delete/<int:id>', ShopDeleteView.as_view(), name='shop_delete'),
    #Shops list url
    path('shop/', ShopListView.as_view(), name='shops_list'),
    #Shop's update url
    path('shop/update/<int:id>', ShopUpdateView.as_view(), name='shop_update'),
    #path('user/', UserView.as_view(), name='user'),
    #User's login url
]

src/minifid/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from managebill.views import IndexView, myLogoutView


# Default's urls
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),
    path('logout/', myLogoutView.as_view(), name='myLogout'),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

# Apps urls
urlpatterns += [
    path('managebill/', include('managebill.urls')),
    path('api/', include('api.urls'), name='api')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/managebill/models.py
from django.db import models
from django.urls import reverse


class Shop(models.Model):
    """
    Implements shops
    """
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)


class Contact(models.Model):
    """
    Implements contacts
    """
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def get_absolute_url(self):
        return reverse('managebill:contacts')

    def __str__(self):
        return str(self.first_name)


class Product(models.Model):
    """
    Implements products
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)


class Bill(models.Model):
    """
    Implements bills
    """
    date = models.DateField(auto_now_add=True)
    ticket_number = models.IntegerField(unique=True)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, related_name='bills', through='BillProduct')

    def __str__(self):
        return str(self.ticket_number)


class BillProduct(models.Model):
    """
    Implements bill products
    """
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return str(self.bill)

src/managebill/forms.py
from django.forms import ModelForm, Select

from .models import  Bill, BillProduct, Contact, Product, Shop


class BillAddProductForm(ModelForm):
    """
    Implements the creation of product to a bill.
    """
    class Meta:
        model = BillProduct
        fields = [
            'bill',
            'product',
            'quantity',
        ]
        widgets = {
            'bill': Select(attrs={
                'disabled': 'true'
                })
        }


class BillForm(ModelForm):
    """
    Implements the creation bill form.
    """
    class Meta:
        model = Bill
        fields = [
            'ticket_number',
            'contact',
            'shop',
        ]


class ContactForm(ModelForm):
    """
    Implements the creation contact form.
    """
    class Meta:
        model = Contact
        fields = [
            'first_name',
            'last_name',
        ]


class ProductForm(ModelForm):
    """
    Implements the creation product form.
    """
    class Meta:
        model = Product
        fields = [
            'name',
        ]


class ShopForm(ModelForm):
    """
    Implements the creation shop form.
    """
    class Meta:
        model = Shop
        fields = [
            'name',
            'address',
        ]

src/managebill/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from .forms import BillAddProductForm, BillForm, ContactForm, ProductForm, ShopForm
from .models import Shop, Contact, Bill, BillProduct, Product


class BillAddProductView(LoginRequiredMixin, CreateView):
    """
    Implements the creation of a product line to a bill.
    """
    form_class = BillAddProductForm
    bill_id = 0
    success_url = reverse_lazy('managebill:bills_list')
    template_name = 'managebill/bill/add-product.html'

    def form_valid(self, form):
        """
        Security check.
        """
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        """
        Overrides dispatch to ....
        """
        _id = kwargs['id']
        self.bill_id = Bill.objects.filter(ticket_number=_id).get().id
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        """
        Overrides get_initial method to populate bill id in form field.
        """
        initial = super(BillAddProductView, self).get_initial()
        initial['bill'] = self.bill_id
        return initial

    def post(self, request, **kwargs):
        """
        Overrides post method to ......
        """
        request.POST = request.POST.copy()
        request.POST['bill'] = self.bill_id
        return super(BillAddProductView, self).post(request, **kwargs)


class BillCreateView(LoginRequiredMixin, CreateView):
    """
    Implements the creation of a bill.
    """
    template_name = 'managebill/bill/create.html'
    form_class = BillForm
    success_url = reverse_lazy('managebill:bills_list')
    queryset = Bill.objects.all()

    def form_valid(self, form):
        """
        Security check.
        """
        return super().form_valid(form)


class BillDetailsView(LoginRequiredMixin, DetailView):
    """
    Implements the view of all products on a bill.
    """
    template_name = 'managebill/bill/details.html'
    context_object_name = 'obj'

    def get_object(self):
        """
        Get the bill's product list
        """
        id_ = self.kwargs.get('id')
        response = Bill.objects.filter(ticket_number=id_).get()
        return response


class BillListView(LoginRequiredMixin, ListView):
    """
    Implements the view of all bills
    """
    template_name = 'managebill/bill/list.html'
    queryset = Bill.objects.all().order_by('contact_id')
    context_object_name = 'obj'


class ContactCreateView(LoginRequiredMixin, CreateView):
    """
    Implements the creation of a contact.
    """
    template_name = 'managebill/contact/create.html'
    form_class = ContactForm
    queryset = Contact.objects.all()

    def form_valid(self, form):
        """
        Security check.
        """
        return super().form_valid(form)


class ContactDeleteView(LoginRequiredMixin, DeleteView):
    """
    Implements the view of the contact's delete.
    """
    template_name = 'managebill/contact/delete.html'
    context_object_name = 'obj'

    def get_object(self):
        """
        Get the contact id to delete.
        """
        id_ = self.kwargs.get('id')
        obj = Contact.objects.filter(id=id_).get()
        return obj

    def get_success_url(self):
        """
        When you delete the contact you are redirected to the contact's list url
        """
        response = reverse('managebill:contacts')
        return response


class ContactUpdateView(LoginRequiredMixin, UpdateView):
    """
    Implements the view of the contact's update
    """
    template_name = 'managebill/contact/update.html'
    form_class = ContactForm
    queryset = Contact.objects.all()
    context_object_name = 'obj'

    def get_object(self):
        """
        Get the contact id to delete.
        """
        id_ = self.kwargs.get('id')
        obj = Contact.objects.filter(id=id_).get()
        return obj

    def form_valid(self, form):
        """
        Security check.
        """
        return super().form_valid(form)


class ContactDetailsView(LoginRequiredMixin, DetailView):
    """
    Implements the view to list all contact's bills.
    """
    template_name = 'managebill/contact/details.html'
    context_object_name = 'obj'

    def get_object(self):
        """
        Get the contact's bill list
        """
        id_ = self.kwargs.get('id')
        response = Bill.objects.filter(contact_id=id_)
        return response


class ContactListView(LoginRequiredMixin, ListView):
    """
    Implements the view to list all contacts.
    """
    context_object_name = 'obj'
    template_name = 'managebill/contact/list.html'
    queryset = Contact.objects.all()


class IndexView(LoginRequiredMixin, TemplateView):
    """
    Implements the view of the index
    """
    template_name = 'managebill/index.html'


class myLogoutView(LogoutView):
    """
    Log out the user and display the 'You are logged out' message.
    """
    next_page = 'login'


class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    Implements the creation of a product
    """
    form_class = ProductForm
    queryset = Product.objects.all()
    success_url = reverse_lazy('managebill:products')
    template_name = 'managebill/product/create.html'


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """
    Implements the view of the product's delete.
    """
    success_url = reverse_lazy('managebill:products')
    template_name = 'managebill/product/delete.html'
    context_object_name = 'obj'

    def get_object(self):
        """
        Get the product id to delete.
        """
        id_ = self.kwargs.get('id')
        obj = Product.objects.filter(id=id_).get()
        return obj


class ProductListView(LoginRequiredMixin, ListView):
    """
    Implements the view for all products available
    """
    context_object_name = 'obj'
    template_name = 'managebill/product/list.html'
    queryset = Product.objects.all().order_by('name')

    def form_valid(self, form):
        """
        TODO
        """
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """
    Implements the view of the contact's update
    """
    context_object_name = 'obj'
    form_class = ProductForm
    queryset = Product.objects.all()
    success_url = reverse_lazy('managebill:products')
    template_name = 'managebill/product/update.html'

    def get_object(self):
        """
        Get the contact id to delete.
        """
        id_ = self.kwargs.get('id')
        obj = Product.objects.filter(id=id_).get()
        return obj

    def form_valid(self, form):
        """
        Security check.
        """
        return super().form_valid(form)


class ShopCreateView(LoginRequiredMixin, CreateView):
    """
    Implements the creation of a shop
    """
    form_class = ShopForm
    queryset = Shop.objects.all()
    success_url = reverse_lazy('managebill:shops_list')
    template_name = 'managebill/shop/create.html'


class ShopDeleteView(LoginRequiredMixin, DeleteView):
    """
    Implements the view of the shop's delete.
    """
    template_name = 'managebill/shop/delete.html'
    context_object_name = 'obj'

    def get_object(self):
        """
        Get the shop id to delete.
        """
        id_ = self.kwargs.get('id')
        obj = Shop.objects.filter(id=id_).get()
        return obj

    def get_success_url(self):
        """
        When you delete the contact you are redirected to the contact's list url
        """
        response = reverse('managebill:shops_list')
        return response


class ShopListView(LoginRequiredMixin, ListView):
    """
    Implements the view for all shops
    """
    context_object_name = 'obj'
    template_name = 'managebill/shop/list.html'
    queryset = Shop.objects.all().order_by('name')


class ShopUpdateView(LoginRequiredMixin, UpdateView):
    """
    Implements the view of the shop's update
    """
    context_object_name = 'obj'
    form_class = ShopForm
    queryset = Shop.objects.all()
    success_url = reverse_lazy('managebill:shops_list')
    template_name = 'managebill/shop/update.html'

    def get_object(self):
        """
        Get the shop id to delete.
        """
        id_ = self.kwargs.get('id')
        obj = Shop.objects.filter(id=id_).get()
        return obj

    def form_valid(self, form):
        """
        Security check.
        """
        return super().form_valid(form)

src/managebill/templates/managebill/contact/create.html
{% extends 'managebill/base.html' %}
{% load static %}

{% block header %}
    <h1>Create a contact</h1>
{% endblock %}

{% block main %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Done" class="btn btn-primary" />
        <a class="btn btn-primary" href="../">Back to contact list</a>
    </form>
{% endblock %}

src/managebill/templates/managebill/contact/delete.html
{% extends 'managebill/base.html' %}
{% load static %}

{% block main %}
<form action="{% url 'managebill:contact_delete' obj.id %}" method="POST" class="form-inline">
    {% csrf_token %}
    <div class="form-group mx-sm-3 mb-2">
        <h4>Are you sure you want to delete {{ obj.first_name }} {{ obj.last_name }} ? </h4>
        <p><input type="submit" value="Delete (Y)" class="btn btn-primary mb-2"/> <a href="../">Cancel</a></p>
    </div>
</form>
{% endblock %}

src/managebill/templates/managebill/contact/details.html
{% extends 'managebill/base.html' %}
{% load static %}


{% block header %}
    {% if obj|length > 0 %}
        <h1>Bills of {{ obj.0.contact.first_name }} {{ obj.0.contact.last_name }}</h1>
    {% else %}
        <h1>This contact don't even have 1 bill :/</h1>
    {% endif %}
{% endblock %}

{% block main %}
    {% if obj|length > 0 %}
        <div style="text-align: center;">
            <table class="table bounceIn animated">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Bills</th>
                    </tr>
                </thead>
                <tbody>
                {% for bill in obj %}
                    <tr>
                        <td><a href="{% url 'managebill:bill_details' bill.ticket_number %}">{{ bill.ticket_number }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div style="text-align: center;">
            <img width=250 src="{% static 'managebill/img/dance_carlton.gif' %}"/>
        </div>
    {% endif %}
<a class="btn btn-danger" href="{% url 'managebill:bill_create' %}">Add a bill</a>
<a class="btn btn-primary" href="{% url 'managebill:contacts' %}">Back to contacts list</a>
<a class="btn btn-primary" href="/">Back to index</a>
{% endblock %}

src/managebill/templates/managebill/contact/list.html
{% extends 'managebill/base.html' %}
{% load static %}

{% block header %}
    <h1 class="bounceInLeft animated">Contact list</h1>
{% endblock %}

{% block main %}
    {% if obj|length > 0 %}
        <table class="table" style="text-align: center;">
            <thead class="thead-dark bounceInLeft animated">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Delete</th>
                    <th scope="col">Update</th>
                </tr>
            </thead>
            <tbody>
            {% for contact in obj %}
                <tr>
                    <td class="bounceIn animated delay-1s">
                        <a href="{% url 'managebill:contact_details' contact.id %}">{{ contact.first_name }} {{  contact.last_name }}</a>
                    </td>
                    <td class="bounceIn animated delay-1s">
                        <a style="color: red;" href="{% url 'managebill:contact_delete' contact.id %}" class="bounceIn animated delay-1s">[X]</a>
                    </td>
                    <td class="bounceIn animated delay-2s">
                        <a style="color: blue;" href="{% url 'managebill:contact_update' contact.id %}">[U]</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h1 class="bounceInLeft animated">There is no contact</h1>
    {% endif %}
    <a class="btn btn-outline-primary bounceInLeft animated" href="{% url 'managebill:contact_create' %}">Create a contact</a>
    <a class="btn btn-primary bounceInLeft animated" href="/">Back to index</a>
{% endblock %}

src/managebill/templates/managebill/contact/update.html
{% extends 'managebill/base.html' %}
{% load static %}

{% block header %}
    <h1>Update {{ obj.first_name }} {{ obj.last_name }}</h1>
{% endblock %}

{% block main %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Done" class="btn btn-primary" />
        <a class="btn btn-primary" href="../">Back to contact list</a>
    </form>
{% endblock %}